### ISSUE TITLE
Spectator Client Crashed when Trade Initiated

### ISSUE THREAD

**Issue by frankobjank** [ashn-dot-dev/natac#18]
A trade offer was sent while I was viewing the game as a spectator. My client crashed and I got this error message in my terminal:
[client.sunder:724] unreachable

**Comment by ashn-dot-dev** [comment]
For reference, this occurred on commit 68bec721d8f425916854c441b753466d842bbbc8.

**Comment by ashn-dot-dev** [comment]
Update - user was running not on commit 68bec721d8f425916854c441b753466d842bbbc8, and was running an old build where the NIL player was part of the `player` enum.
